### ISSUE TITLE
ValueError: unsupported pickle protocol:3

### ISSUE THREAD

**Issue by developerChenRui** [ftrang88/EC601-Fall2017-Seamless-Track-Detection#12]
When I run the program in python 2.7 environment, it will raise ValueError when using pickle
save_dict=pickle.load(f)
and I think this is due to the version of python.

**Comment by developerChenRui** [comment]
Generally speaking, this project is very cool and the images and videos can clearly show the function of your program.
Looking forward your sprint3!

**Comment by DonatoK** [comment]
Yes,  the program is for python3 thank you
