### ISSUE TITLE
raise NeedDownloadError

### ISSUE THREAD

**Issue by x2mercy** [ftrang88/EC601-Fall2017-Seamless-Track-Detection#13]
After I installed moviepy and tried to run the program, it raised an error called "NeedDownloadError: Need ffmpeg exe. You can download it by calling:
imageio.plugins.ffmpeg.download()"
It could be fixed by add 2 lines before from moviepy.editor import VideoFileClip:
import imageio
imageio.plugins.ffmpeg.download()

**Comment by x2mercy** [comment]
The folders in this repository aren't organized clearly and this makes users hard to know how to use.

**Comment by x2mercy** [comment]
The folders in this repository aren't organized clearly and this makes users hard to know how to use

**Comment by DonatoK** [comment]
Hi, What file are you adding those two lines of code to?
